server:
  http:
    host: ""
    port: "8080"
    env: "dev"
databases:
  mysql:
    username: root
    password: 12345678
    host: 127.0.0.1
    port: "3306"
    dbname: rabit_api
    # dsn: "root:12345678@tcp(127.0.0.1:3306)/rabit_api?charset=utf8mb4&parseTime=True&loc=Local"
    maxLifeTime: 4 # hour
    maxIdleConn: 200
    maxOpenConn: 200
