system:
  ip: "127.0.0.1"
  port: 8089
  env: dev
mysql:
  host: 127.0.0.1   # 不另外设置时，默认为127.0.0.1
  post: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db: testdb
  username: root
  password: 12345678
  logLevel: error
redis:
  ip: 127.0.0.1
  port: 6379
  password: ""
  poolSize: 100
jwt:
  expires: 2  # 过期时间（hour）
  issuer: "guanji"  # 签发人
  secret: "uid*api*pwd&GJ"  # 密钥